build(linux_targz): change install and uninstall files
Add rsised-mime.xml.in
Add /usr/lib/qt/plugins/kf5/

diff --git a/src/rsised/install.sh.in b/src/rsised/install.sh.in
--- a/src/rsised/install.sh.in
+++ b/src/rsised/install.sh.in
@@ -29,21 +29,15 @@
 # Email: <ermolovva@gmail.com>                                                          #
 #########################################################################################
 
-set -Eeuo pipefile # stop on error
+set -Eeuo pipefail # stop on error
 
 # [VARIABLE]
-#VERSION='"$$VERSION"'
 APP='$$APPLICATION_NAME'
-EXT=rse
-#EXEC=/usr/bin/${APP}
 SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
-#echo "SCRIPT_DIR = "${SCRIPT_DIR}
 LOGO_PATH=${SCRIPT_DIR}/icons
-#ICONS_PATH=/usr/share/icons/hicolor
-DESKTOP_PATH=${HOME}/.local/share/applications
+DESKTOP_PATH=/usr/share/applications
 INSTALL_PATH=/opt/${APP}
 LINK_PATH=/usr/bin/${APP}
-COMMENT='"$$DESCRIPTION"'
 
  cleanup() {
  if [ -d ${INSTALL_PATH} ]; then
@@ -74,6 +68,8 @@ mkdir -v ${INSTALL_PATH}
 cp -v ${SCRIPT_DIR}/rsised.sh ${INSTALL_PATH}
 chmod u+x ${SCRIPT_DIR}/uninstall.sh
 cp -v ${SCRIPT_DIR}/uninstall.sh ${INSTALL_PATH}
+cp -v ${SCRIPT_DIR}/${APP}-mime.xml ${INSTALL_PATH}
+cp -v ${SCRIPT_DIR}/README ${INSTALL_PATH}
 cp -rv ${SCRIPT_DIR}/plugins ${INSTALL_PATH}
 cp -rv ${SCRIPT_DIR}/lib ${INSTALL_PATH}
 cp -rv ${SCRIPT_DIR}/bin ${INSTALL_PATH}
@@ -82,42 +78,24 @@ chmod a+x ${LINK_PATH}
 echo '"Copying files to the ${INSTALL_PATH} directory completed"'
 
 # [ICONS]
-#cp -v ${SCRIPT_DIR}/icons/32x32/rsised.png ${ICONS_PATH}/32x32/apps
-#cp -v ${SCRIPT_DIR}/icons/48x48/rsised.png ${ICONS_PATH}/48x48/apps
-#cp -v ${SCRIPT_DIR}/icons/64x64/rsised.png ${ICONS_PATH}/64x64/apps
-#cp -v ${SCRIPT_DIR}/icons/128x128/rsised.png ${ICONS_PATH}/128x128/apps
-#cp -v ${SCRIPT_DIR}/icons/256x256/rsised.png ${ICONS_PATH}/256x256/apps
-#cp -v ${SCRIPT_DIR}/icons/scalable/rsised.svg ${ICONS_PATH}/scalable/apps
 xdg-icon-resource install --context mimetypes --size 32 ${LOGO_PATH}/32x32/${APP}.png application-x-${APP}
 xdg-icon-resource install --context mimetypes --size 48 ${LOGO_PATH}/48x48/${APP}.png application-x-${APP}
 xdg-icon-resource install --context mimetypes --size 64 ${LOGO_PATH}/64x64/${APP}.png application-x-${APP}
 xdg-icon-resource install --context mimetypes --size 128 ${LOGO_PATH}/128x128/${APP}.png application-x-${APP}
 xdg-icon-resource install --context mimetypes --size 256 ${LOGO_PATH}/256x256/${APP}.png application-x-${APP}
 echo '"Registration of application icons completed"'
+echo '"Please wait"'
 
 # [MIME]
-echo '"<?xml version=\"1.0\" encoding=\"UTF-8\"?>'
-'<mime-info xmlns=\"http://www.freedesktop.org/standards/shared-mime-info\">'
-    '<mime-type type=\"application/x-${APP}\">'
-        '<comment>${COMMENT}</comment>'
-        '<icon name=\"application-x-${APP}\"/>'
-        '<glob pattern=\"*.${EXT}\"/>'
-    '</mime-type>'
-'</mime-info>"' > ${APP}-mime.xml
-
 xdg-mime install ${APP}-mime.xml
-rm ${APP}-mime.xml
-update-mime-database $HOME/.local/share/mime
+update-mime-database /usr/share/mime
 echo '"The ${APP}-mime.xml file is installed, mime database is update"'
 
 # [DESKTOP]
-#cp -v rsised.desktop ${DESKTOP_PATH}
 desktop-file-install --dir=${DESKTOP_PATH} ${SCRIPT_DIR}/${APP}.desktop
 update-desktop-database ${DESKTOP_PATH}
 echo '"The ${APP}.desktop file is installed, desktop database is update"'
 
 xdg-mime default ${APP}.desktop application/x-${APP}
-
-#gtk-update-icon-cache ${ICONS_PATH}
 
 echo '"Application installation completed successfully!"'
diff --git a/src/rsised/uninstall.sh.in b/src/rsised/uninstall.sh.in
--- a/src/rsised/uninstall.sh.in
+++ b/src/rsised/uninstall.sh.in
@@ -29,14 +29,11 @@
 # Email: <ermolovva@gmail.com>                                                          #
 #########################################################################################
 
-set -Eeuo pipefile # stop on error
+set -Eeuo pipefail # stop on error
 
 # [VARIABLE]
-#SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
-#echo "SCRIPT_DIR = "${SCRIPT_DIR}
 APP='$$APPLICATION_NAME'
-#ICONS_PATH=/usr/share/icons/hicolor
-DESKTOP_PATH=${HOME}/.local/share/applications
+DESKTOP_PATH=/usr/share/applications
 INSTALL_PATH=/opt/${APP}
 LINK_PATH=/usr/bin/${APP}
 
@@ -49,22 +46,19 @@ if [[ $EUID -ne 0 ]]; then
 fi
 
 # [REMOVE ICONS]
-#rm -v ${ICONS_PATH}/32x32/apps/rsised.png
-#rm -v ${ICONS_PATH}/48x48/apps/rsised.png
-#rm -v ${ICONS_PATH}/64x64/apps/rsised.png
-#rm -v ${ICONS_PATH}/128x128/apps/rsised.png
-#rm -v ${ICONS_PATH}/256x256/apps/rsised.png
-#rm -v ${ICONS_PATH}/scalable/apps/rsised.png
 xdg-icon-resource uninstall --context mimetypes --size 32 application-x-${APP}
 xdg-icon-resource uninstall --context mimetypes --size 48 application-x-${APP}
 xdg-icon-resource uninstall --context mimetypes --size 64 application-x-${APP}
 xdg-icon-resource uninstall --context mimetypes --size 128 application-x-${APP}
 xdg-icon-resource uninstall --context mimetypes --size 256 application-x-${APP}
 echo '"App icons removed"'
+echo '"Please wait"'
 
 # [MIME]
-xdg-mime uninstall ${APP}-mime.xml
-echo '"File ${APP}-mime.xml removed"'
+if [ -f ${INSTALL_PATH}/${APP}-mime.xml ]; then
+    xdg-mime uninstall ${INSTALL_PATH}/${APP}-mime.xml
+    echo '"Removes the file type descriptions provided in ${APP}-mime.xml"'
+fi
 
 # [DESKTOP]
 if [ -f ${DESKTOP_PATH}/${APP}.desktop ]; then
