build(linux_targz): Edit installation and uninstallation scripts
Application installation and uninstallation scripts are generated
automatically by the qmake system.

diff --git a/src/rsised/uninstall.sh.in b/src/rsised/uninstall.sh.in
--- a/src/rsised/uninstall.sh.in
+++ b/src/rsised/uninstall.sh.in
@@ -1,31 +1,80 @@
 #!/bin/bash
 
-iconsPath="/usr/share/icons/hicolor"
-desktopPath="/usr/share/applications"
-installPath="/opt/rsised"
-linkPath="/usr/bin/rsised"
-echo "rsised uninstall"
+#########################################################################################
+# File: uninstall.sh.in                                                                 #
+#                                                                                       #
+# Description: This file is used to automatically generate (rsised.pro section [DEPOY]) #
+# an application uninstallation script (uninstall.sh) from the linux_targz distribution.#
+#                                                                                       #
+# Created: June 30 2023                                                                 #
+#                                                                                       #
+# Copyright: (c) 2022 by Viktor Ermolov <ermolovva@gmail.com>.                          #
+#                                                                                       #
+# This file is part of the RSiSed project, a editor of the alignment of forces          #
+# and means in extinguishing a fire. (RSiSed)                                           #
+#                                                                                       #
+# RSiSed is free software: you can redistribute it and/or modify                        #
+# it under the terms of the GNU General Public License as published by                  #
+# the Free Software Foundation, either version 3 of the License, or                     #
+# (at your option) any later version.                                                   #
+#                                                                                       #
+# RSiSed is distributed in the hope that it will be useful,                             #
+# but WITHOUT ANY WARRANTY; without even the implied warranty of                        #
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the                          #
+# GNU General Public License for more details.                                          #
+#                                                                                       #
+# You should have received a copy of the GNU General Public License                     #
+# along with this program.  If not, see <https://www.gnu.org/licenses/>.                #
+#                                                                                       #
+# Email: <ermolovva@gmail.com>                                                          #
+#########################################################################################
 
-#Check user
+set -Eeuo pipefile # stop on error
+
+# [VARIABLE]
+#SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
+#echo "SCRIPT_DIR = "${SCRIPT_DIR}
+APP='$$APPLICATION_NAME'
+#ICONS_PATH=/usr/share/icons/hicolor
+DESKTOP_PATH=/usr/share/applications
+INSTALL_PATH=/opt/${APP}
+LINK_PATH=/usr/bin/${APP}
+
+echo '"The uninstallation of the ${APP} application has begun"'
+
+# [CHECK USER]
 if [[ $EUID -ne 0 ]]; then
     echo "This script must be run as root"
     exit 1
 fi
 
-rm -v $iconsPath'/32x32/apps/rsised.png'
-rm -v $iconsPath'/48x48/apps/rsised.png'
-rm -v $iconsPath'/64x64/apps/rsised.png'
-rm -v $iconsPath'/72x72/apps/rsised.png'
-rm -v $iconsPath'/96x96/apps/rsised.png'
-rm -v $iconsPath'/128x128/apps/rsised.png'
-rm -v $iconsPath'/256x256/apps/rsised.png'
-rm -v $iconsPath'/512x512/apps/rsised.png'
-rm -v $iconsPath'/scalable/apps/rsised.png'
-rm -v $desktopPath'/rsised.desktop'
+# [REMOVE ICONS]
+#rm -v ${ICONS_PATH}/32x32/apps/rsised.png
+#rm -v ${ICONS_PATH}/48x48/apps/rsised.png
+#rm -v ${ICONS_PATH}/64x64/apps/rsised.png
+#rm -v ${ICONS_PATH}/128x128/apps/rsised.png
+#rm -v ${ICONS_PATH}/256x256/apps/rsised.png
+#rm -v ${ICONS_PATH}/scalable/apps/rsised.png
+xdg-icon-resource uninstall --context mimetypes --size 32 application-x-${APP}
+xdg-icon-resource uninstall --context mimetypes --size 48 application-x-${APP}
+xdg-icon-resource uninstall --context mimetypes --size 64 application-x-${APP}
+xdg-icon-resource uninstall --context mimetypes --size 128 application-x-${APP}
+xdg-icon-resource uninstall --context mimetypes --size 256 application-x-${APP}
+echo '"App icons removed"'
 
-#Remove app folder
-echo "---"
-rm -rfv $installPath
-rm -v  $linkPath
+# [MIME]
+xdg-mime uninstall ${APP}-mime.xml
+echo '"File ${APP}-mime.xml removed"'
 
-echo "Uninstall finished!"
+# [DESKTOP]
+if [ -f ${DESKTOP_PATH}/${APP}.desktop ]; then
+    rm -v ${DESKTOP_PATH}/${APP}.desktop
+    echo '"File ${APP}.desktop removed"'
+fi
+
+# [REMOVE APP]
+rm -rfv ${INSTALL_PATH}
+rm -v  ${LINK_PATH}
+echo '"Directory ${INSTALL_PATH} removed"'
+
+echo '"Uninstall ${APP} finished!"'
